"""crear tabla inscripciones

Revision ID: bb048049015d
Revises: b1f4b9af10a7
Create Date: 2026-03-05 15:41:23.730683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb048049015d'
down_revision = 'b1f4b9af10a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maestro_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('maestro_id')

    # ### end Alembic commands ###
